#!/bin/bash
#SBATCH --job-name=amy_thin_test
#SBATCH --output=/fslustre/qhs/ext_chen_yuheng_mayo_edu/script/out/amy_thin_test_%j.out
#SBATCH --partition=gpu-n64-240g-4x-tesla-t4
#SBATCH --gres=gpu:1
#SBATCH --mem=200G
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8

# --- Configuration ---
TARGET_FILE="/fslustre/qhs/ext_chen_yuheng_mayo_edu/Amyloid_Slides/tiff/NA01-161_H02P23TB517P-193924_level-0.tiff"

# This path contains the folders generated by your inference_test.py
MASK_ROOT_DIR="/fslustre/qhs/ext_chen_yuheng_mayo_edu/Amyloid_Slides/prediction_priority_threshold_wmw_1.5_gmt_0.2_wmt_0.2_clean_21_best_parameter"
OUTPUT_DIR="/fslustre/qhs/ext_chen_yuheng_mayo_edu/Amyloid_Slides/amyloid_predictions_test_aggressive_cleanup_v4"
MODEL_PATH="/fslustre/qhs/ext_chen_yuheng_mayo_edu/RO1_CNN/RO1_Amyloid_testing/log_new_data_with_edges/last.ckpt"

echo "Processing ONLY: $TARGET_FILE"

# --- Environment ---
source ~/miniconda3/etc/profile.d/conda.sh
conda activate rhizonet

# --- Execution ---
# Added --test_mode flag here
python /fslustre/qhs/ext_chen_yuheng_mayo_edu/rhizonet/rhizonet/predict_amyloid_thin_slides.py \
    --tiff_path "$TARGET_FILE" \
    --mask_root_dir "$MASK_ROOT_DIR" \
    --output_dir "$OUTPUT_DIR" \
    --model_path "$MODEL_PATH" \
    --resolution 0.2827 \
    --model_input_size 128 \
    --gm_threshold 0.9 \
    --blur_strength 0 \
    --min_grain_size 100 \
    --test_mode